### PR TITLE
Port To Python 3

### PR DESCRIPTION
**Pull request by Creatune**
Gave the error "Event queue full!" but after editing a bit more, it stopped giving the error. I also ran the game and played to check if there were any errors. I didn't see any. So here is the PR :)
I apologise for the inappropriate commit name.

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Porting from Sugargame v1.1 to v1.3 would usually require other changes in the activity.  Please review the changes in Sugargame (i.e. read the commits there and the release notes) to figure out what else you need to do.

**Comment by ayushnawal** [comment]
@Creatune after updating the sugargame source files, does this error comes up?
`AttributeError: 'PygameCanvas' object has no attribute 'run_pygame'`

Have you tested the activity after the changes you made?

**Comment by Creatune** [comment]
I didn't fully test it yet. I will get back to this repo later. That is why it is a draft PR :)

**Comment by Creatune** [comment]
I will work on all the other errors that will come and mark this PR for review after I solve them.

**Pull request closed without merging**
