### PR TITLE
Port to Python 3

### LINKED ISSUE #12: Port to python 3.

### PR DESCRIPTION
**Pull request by kiy4h**
Tested.
Closes #12

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Please use the Sugargame source from the Sugargame repository rather than porting the source in this repository.  I noticed because you changed the pygame.event.Event argument name from unicode to str, and that's not in the [API](https://www.pygame.org/docs/ref/event.html).

**Comment by kiy4h** [comment]
@quozl Sorry about that, thanks for pointing it out. I'll fix it soon.

**Comment by quozl** [comment]
Thanks.  An update from Sugargame 1.1 to 1.3 requires a few other changes to main.py, please read and understand the commits in Sugargame over that interval, and check against the test activity there.  In particular the pygame.init should not be in the run method, but there may be some other things to change.  Otherwise the game can perform badly under certain timing circumstances, and may consume CPU time.

**Comment by kiy4h** [comment]
Whoops, I forget to test after applying changes.
@quozl this might be a dumb question, but what should I change this line into?

https://github.com/Kiy4h/dotsAndBoxes/blob/python3/activity.py#L54

I have tried removing the line 54 and changing line 51 to 
```python3
        self.game.canvas = sugargame.canvas.PygameCanvas(
            self, main=self.game.run, modules=[pygame.display, pygame.font]
        )
```

but after testing the canvas wasn't rendered. Is anything causing this?
I'll continue searching for the cause.

**Comment by kiy4h** [comment]
After a bit of testing, I think the pygame.init should be in the run function, if not it will just start a new pygame window and messes everything up.

I think what's important is that it's not in the `while run` loop, do you think so?

**Comment by quozl** [comment]
You'll see in the Sugargame 1.3 test activity that pygame.init is not called, but that PygameCanvas calls the individual pygame.MODULE.init functions.  This was done in 9f816dc52fba706ff252a8a599398eec502b6234 and fixed visual lag during startup in c12bb30f9ddf756796404f1ed919e64eea86a8dc.  Along with 1561b817fb81dc4b1f01bb65128268eb2b6de099 it allowed running activities without audio or mixer when they didn't provide sound effects.

If after doing it right in the PygameCanvas something isn't being rendered, it probably means something else isn't being done right.

When a new pygame window appears it means the Gtk.Socket isn't intervening.

Does the Sugargame test activity work properly on your test platform?

**Comment by kiy4h** [comment]
The Sugargame test activity worked well on the VM, I think the pygame window was opened because I moved the `pygame.init` line to the `main.Game.__init__` function, since I was testing everything out. Removing it fixes it.

This is what's currently seen after running the activity:

image

The screen freezes, just like that.

If you'd like to see my progress, you can see it here: https://github.com/Kiy4h/dotsAndBoxes/commit/579b324e31a4177d4485dbffc6d21fb8c7d4f1db

I added the `__configure_cb` function to the Activity class, which auto-refresh the pygame settings. To my surprise, the screen turns black when I changed the screen resolution:

image

and the game renders correctly when I changed any of the "color" settings:

image

**Comment by quozl** [comment]
Thanks.  On your vmtest branch hash 579b324 I did iterate through the differences against the test activity, and found the following change does fix the black screen;

```diff
diff --git a/activity.py b/activity.py
index d713123..f8414dd 100755
--- a/activity.py
+++ b/activity.py
@@ -115,8 +115,6 @@ class Activity(activity.Activity):
         toolbar_box.toolbar.insert(stop_button, -1)
         stop_button.show()
 
-        self.show_all()
-
     def build_size_toolbar(self, toolbox):
 
         size_bar = Gtk.Toolbar()
```

I stopped iterating at that point.  Please try the change and let me know what you find in your environment.

I'm surprised at the use of the Gdk.Screen _size-changed_ event as I thought Pygame handled that with the `pygame.VIDEORESIZE` event, but I see you don't detect that event in the Pygame event loop yet.  Does the test activity handle the display resize?  What method do you use to change display size?  I usually use `xrandr`.

**Comment by quozl** [comment]
Hey, by the way, the removal of `show_all` was in the Sugargame changes between v1.1 and v1.2, see https://github.com/sugarlabs/sugargame/commit/3981fa2562bdc0b229d911b038e0ce9c4f252713 ("Test activity port to new toolbars").  It should probably have been done in f6de4c1dc98112de8d88783b8f0d58891af5b62e ("Port to GTK 3").

**Comment by kiy4h** [comment]
@quozl I understand now, thanks for taking your time to explain it. I'll push a fix soon, rebase, and cherry-pick the vmtest branch.

**Comment by quozl** [comment]
Thanks.  Tested.  No issues with black screen or startup.  Jams the CPU on though; perhaps the Pygame clock is too high.  A two by two or three by three box grid didn't seem to have the right hotspots for drawing boxes.  Was this result of porting?

**Comment by kiy4h** [comment]
@quozl The 3x3 - 2x2 box grid issue has been reported on #16, it was a known bug.
About the clock, I realized that I haven't called it in `while run`.

**Comment by kiy4h** [comment]
@quozl CPU usage has gone down, tell me what you think!

**Pull request merged**
