### PR TITLE
Dev

### LINKED ISSUE #11: Make a release.
@nswarup14 you might be interested. Thanks!

### LINKED ISSUE #16: Changing the H and V values to 2 mess up the lines
When I set the H and V values to 2 in the settings, the lines will be misaligned, and some lines can be created on the area that doesn't contain dots:

image

This still happens even after creating a new game.

### PR DESCRIPTION
**Pull request by JuiP**
- [x] commit 11706fc Fixes #16 

- [x] Fix IndexError

Traceback (most recent call last):
File "/usr/share/sugar/activities/dotsAndBoxes.activity/main.py", line 366, in run
ret = self.where(pos)
File "/usr/share/sugar/activities/dotsAndBoxes.activity/main.py", line 211, in where
b = self.boxes[x_b][y_b]
IndexError: list index out of range

Seen when H and V values are changed mid game. The fix seems small but took me time to figure out the cause. Initially I thught it was a port to python3 regression but wasn't.

- [x] Release v4 (Closes #11)

@quozl @chimosky Please test, review and merge :)

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Tested.  Please put traceback from first pull request comment into commit message of patch that fixes it?

**Comment by JuiP** [comment]
@quozl done in dabbb80

**Review by Saumya-Mishra9129 — APPROVED** [review]

**Comment by quozl** [comment]
Re: https://github.com/sugarlabs/dotsAndBoxes/commit/dabbb8065dcf99d295879032ce8ad1ed61162494 the traceback has lost indentation; the usual cognitive process that processes the traceback is challenged or reduced by the change to indentation.

**Comment by JuiP** [comment]
@quozl done

**Comment by quozl** [comment]
Thanks.  Reviewed.  Approved.

**Pull request merged**
